version: "3"

networks:
  MainNetwork:

services:
  ZIDAutomatBackend:
    image: maxi1324/zidautomatapi:latest
    ports:
      - 801:80
    depends_on:
      - MySqlServer
    volumes:
      - ./Certificates:/Certificates
      - ./properties:/app/properties
    environment:
      - UseDatabase=MySql
      - ConnectionString=Server=MySqlServer;Port=3306;Database=AutoamtDatabase4;Uid=root;Pwd=your_root_password;
      - CertificatPassword=${CertificatPassword}
      - AdminHall=${AdminHall}
      - AutomatPassword=${AutomatPassword}
      - JWTSecret=${JWTSecret}
      - CorsOrigin=https://localhost:4200;https://localhost:4201;http://localhost:4201;http://localhost:4200
      - Urls=http://*:80
    networks:
      - MainNetwork

  MySqlServer:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=AutoamtDatabase4
      - MYSQL_USER=your_username
      - MYSQL_PASSWORD=your_password
    
    networks:
      - MainNetwork
    volumes:
      - ./Database:/var/lib/mysql
